@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.halffocused.diamond_is_uncraftable.world.dimension;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;