@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.halffocused.diamond_is_uncraftable.entity.stand.attack;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;