modLoader="javafml" #mandatory

loaderVersion="[36,)"

issueTrackerURL="https://github.com/HalfFocused/Diamond-is-Uncraftable/issues"

license="MIT"

[[mods]]

modId="diamond_is_uncraftable"

version="1.16.5-0.0.6.0"

displayName="Diamond is Uncraftable"

updateJSONURL="http://example.com/"

displayURL="https://github.com/HalfFocused/Diamond-is-Uncraftable"

logoFile="logo.png"

credits="HalfFocused (coding), Joejan (models), DELTA & the17kyd (sounds), Droidy365 (mod logo), samuraii (mod icon)"

authors="HalfFocused, Joejan"

description='''
	An animated pvp mod inspired by JoJo's Bizarre Adventure that adds many stands from the series.
	The mod is primarily balanced around the player-versus-player experience.
'''

[[dependencies.diamond_is_uncraftable]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.diamond_is_uncraftable]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
