@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.halffocused.diamond_is_uncraftable.client.entity.model;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;