@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.halffocused.diamond_is_uncraftable.effect;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;