@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.halffocused.diamond_is_uncraftable.config;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;