@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package io.github.halffocused.diamond_is_uncraftable.entity.stand;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;